# Generated by Django 5.2.11 on 2026-02-27 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
        migrations.AlterField(
            model_name='businesssubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesssubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='businesssubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
