# Generated by Django 5.2.11 on 2026-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_package_max_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_tables',
            field=models.IntegerField(),
        ),
    ]
