# Generated by Django 5.2.11 on 2026-03-28 14:37

import subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_package_max_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to=subscription.models.cloudinary_original_path),
        ),
    ]
