# Generated by Django 5.2.11 on 2026-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_package_max_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_products',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
