# Generated by Django 5.2.11 on 2026-03-28 15:25

import subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscriptionpayment_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_proof',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=subscription.models.cloudinary_original_path),
        ),
    ]
