# Generated by Django 5.2.11 on 2026-03-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_package_max_products'),
        ('subscription', '0006_alter_subscriptionpayment_payment_proof'),
    ]

    operations = [
    ]
