# Generated by Django 5.2.11 on 2026-03-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_brand_itemvariant_purchase_purchaseitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='size',
        ),
    ]
