# Generated by Django 5.2.11 on 2026-03-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_itemvariant_color_remove_itemvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='barcode_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
