# Generated by Django 5.2.11 on 2026-03-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_itemvariant_color_remove_itemvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('RESELLABLE', 'Resellable'), ('DAMAGED', 'Damaged')], max_length=20, null=True),
        ),
    ]
