# Generated by Django 5.2.11 on 2026-03-28 14:37

import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_merge_0005_itemvariant_barcode_image_0014_supplier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pos.models.cloudinary_original_path),
        ),
    ]
