# Generated by Django 5.2.11 on 2026-03-28 15:23

import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=pos.models.cloudinary_original_path),
        ),
    ]
