# Generated by Django 5.2.11 on 2026-03-28 15:34

import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=pos.models.cloudinary_thumbnail_path),
        ),
    ]
