# Generated by Django 5.2.11 on 2026-03-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_item_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='thumbnail',
        ),
    ]
