# Generated by Django 5.2.11 on 2026-03-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_purchaseitem_selling_price'),
        ('pos', '0019_remove_item_thumbnail'),
    ]

    operations = [
    ]
