# Generated by Django 5.2.11 on 2026-03-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_merge_20260330_1753'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockbatch',
            new_name='pos_stockba_busines_df33fb_idx',
            old_name='pos_stockbat_busines_69bf73_idx',
        ),
        migrations.RenameIndex(
            model_name='stockbatch',
            new_name='pos_stockba_variant_1f7971_idx',
            old_name='pos_stockbat_variant_72b74f_idx',
        ),
        migrations.RenameIndex(
            model_name='stockbatch',
            new_name='pos_stockba_busines_57605e_idx',
            old_name='pos_stockbat_busines_d2ecb1_idx',
        ),
    ]
