# Generated by Django 5.2.11 on 2026-03-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_business_citizenship_thumbnail_and_more'),
        ('pos', '0021_rename_pos_stockbat_busines_69bf73_idx_pos_stockba_busines_df33fb_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('business', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('business', 'category', 'name')},
        ),
    ]
