from django.urls import path

from . import views, views_cashier

urlpatterns = [
    path("", views.inventory_dashboard, name="clothing_inventory_dashboard"),
    path("", views.inventory_dashboard, name="inventory_dashboard"),
    path("inventory/", views.inventory_dashboard, name="clothing_inventory_dashboard_inventory"),
    path("inventory/dashboard/", views.inventory_dashboard, name="clothing_inventory_dashboard_inventory_dashboard"),
    path("inventory_dashboard/", views.inventory_dashboard, name="clothing_inventory_dashboard_legacy"),
    path("inventory_dasgboard/", views.inventory_dashboard, name="inventory_dasgboard"),
    path("products/", views.product_list, name="clothing_product_list"),
    path("products/create/", views.product_create, name="clothing_product_create"),
    path("products/<int:product_id>/", views.product_detail, name="clothing_product_detail"),
    path("products/<int:product_id>/edit/", views.product_edit, name="clothing_product_edit"),
    path("variants/", views.variant_list, name="clothing_variant_list"),
    path("products/<int:product_id>/variants/create/", views.variant_create, name="clothing_variant_create"),
    path("products/<int:product_id>/variants/<int:variant_id>/edit/", views.variant_edit, name="clothing_variant_edit"),
    path("products/<int:product_id>/variants/<int:variant_id>/delete/", views.variant_delete, name="clothing_variant_delete"),
    path("stock-movements/", views.stock_movement_list, name="clothing_stock_movements"),
    path("stock-adjustments/create/", views.stock_adjustment_create, name="clothing_stock_adjustment_create"),
    path("purchases/", views.purchase_list, name="clothing_purchase_list"),
    path("purchases/create/", views.purchase_create, name="clothing_purchase_create"),
    path("purchases/<int:purchase_id>/", views.purchase_detail, name="clothing_purchase_detail"),
    path("purchases/<int:purchase_id>/edit/", views.purchase_edit, name="clothing_purchase_edit"),
    path("purchases/<int:purchase_id>/receive/", views.purchase_receive, name="clothing_purchase_receive"),
    path("suppliers/", views.supplier_list, name="clothing_supplier_list"),
    path("suppliers/create/", views.supplier_create, name="clothing_supplier_create"),
    path("suppliers/<int:supplier_id>/edit/", views.supplier_edit, name="clothing_supplier_edit"),
    path("suppliers/<int:supplier_id>/delete/", views.supplier_delete, name="clothing_supplier_delete"),
    path("low-stock/", views.low_stock_alert, name="clothing_low_stock"),

    # Cashier Panel URLs
    path("cashier/", views_cashier.cashier_dashboard, name="clothing_cashier_dashboard"),
    path("cashier/pos/", views_cashier.pos_new_sale, name="clothing_cashier_pos"),
    path("cashier/sales-history/", views_cashier.sales_history, name="clothing_cashier_sales_history"),
    path("cashier/customers/", views_cashier.customers, name="clothing_cashier_customers"),
    path("cashier/receipt/<int:invoice_id>/", views_cashier.receipt, name="clothing_cashier_receipt"),
    path("cashier/profile/", views_cashier.profile, name="clothing_cashier_profile"),

    # AJAX endpoints for cashier
    path("cashier/api/search-products/", views_cashier.search_products, name="clothing_cashier_search_products"),
    path("cashier/api/add-to-cart/", views_cashier.add_to_cart, name="clothing_cashier_add_to_cart"),
    path("cashier/api/update-cart/", views_cashier.update_cart_item, name="clothing_cashier_update_cart"),
    path("cashier/api/remove-cart/", views_cashier.remove_cart_item, name="clothing_cashier_remove_cart"),
    path("cashier/api/get-cart/<int:order_id>/", views_cashier.get_cart, name="clothing_cashier_get_cart"),
    path("cashier/api/apply-promo/", views_cashier.apply_promo_code, name="clothing_cashier_apply_promo"),
    path("cashier/api/apply-loyalty/", views_cashier.apply_loyalty_points, name="clothing_cashier_apply_loyalty"),
    path("cashier/api/select-customer/", views_cashier.select_customer, name="clothing_cashier_select_customer"),
    path("cashier/api/complete-sale/", views_cashier.complete_sale, name="clothing_cashier_complete_sale"),
    path("cashier/api/update-customer/", views_cashier.update_customer, name="clothing_cashier_update_customer"),
    path("cashier/api/loyalty-history/", views_cashier.loyalty_history, name="clothing_cashier_loyalty_history"),
    path("cashier/api/sale-details/", views_cashier.sale_details, name="clothing_cashier_sale_details"),
    path("cashier/api/update-profile/", views_cashier.update_profile, name="clothing_cashier_update_profile"),
    path("cashier/api/change-password/", views_cashier.change_password, name="clothing_cashier_change_password"),
]
