# Generated by Django 5.2.11 on 2026-03-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
        ('pos', '0004_remove_itemvariant_color_remove_itemvariant_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingVariantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.color')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.size')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_detail', to='pos.itemvariant')),
            ],
        ),
    ]
