# Generated by Django 6.0.3 on 2026-03-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothing", "0003_cashiercustomer_cashierloyaltytransaction_and_more"),
        ("core", "0002_businesstype_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashiercustomer",
            name="purchase_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ClothingLoyaltySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_per_100",
                    models.PositiveIntegerField(
                        default=1, help_text="Points earned per Rs. 100 spent"
                    ),
                ),
                (
                    "point_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Rs. value of 1 loyalty point",
                        max_digits=6,
                    ),
                ),
                (
                    "tier1_purchases",
                    models.PositiveIntegerField(
                        default=5, help_text="Purchases needed for tier-1 discount"
                    ),
                ),
                (
                    "tier1_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Tier-1 discount %",
                        max_digits=5,
                    ),
                ),
                (
                    "tier2_purchases",
                    models.PositiveIntegerField(
                        default=10, help_text="Purchases needed for tier-2 discount"
                    ),
                ),
                (
                    "tier2_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Tier-2 discount %",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothing_loyalty",
                        to="core.business",
                    ),
                ),
            ],
        ),
    ]
