# Generated by Django 4.2.28 on 2026-03-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_remove_itemvariant_color_remove_itemvariant_size"),
        ("clothing", "0003_offer_offerusage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="variants",
            field=models.ManyToManyField(
                blank=True, related_name="variant_offers", to="pos.itemvariant"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "Percentage Discount"),
                    ("FLAT", "Flat Discount"),
                    ("PRODUCT", "Product Wise Offer"),
                    ("VARIANT", "Variant Wise Offer"),
                    ("CATEGORY", "Category Wise Offer"),
                    ("SEASONAL", "Seasonal/Festival Offer"),
                    ("LOYALTY", "Customer Loyalty Discount"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_offers",
                to="pos.item",
            ),
        ),
    ]
