# Generated by Django 6.0.3 on 2026-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothing", "0004_loyalty_setting_and_purchase_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashiercustomer",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
