# Generated by Django 4.2.28 on 2026-03-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_businesstype_code"),
        ("clothing", "0004_offer_variants_alter_offer_offer_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("OFFER_CREATED", "Offer Created"),
                            ("OFFER_EXPIRING", "Offer Expiring Soon"),
                            ("OFFER_EXPIRED", "Offer Expired"),
                            ("LOW_STOCK", "Low Stock Alert"),
                            ("PURCHASE_RECEIVED", "Purchase Received"),
                            ("GENERAL", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.business"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "is_read", "created_at"],
                        name="clothing_no_busines_b179b8_idx",
                    )
                ],
            },
        ),
    ]
