# Generated by Django 6.0.3 on 2026-03-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothing", "0005_fix_customer_phone_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothingloyaltysetting",
            name="tier1_purchases",
        ),
        migrations.RemoveField(
            model_name="clothingloyaltysetting",
            name="tier2_purchases",
        ),
        migrations.AddField(
            model_name="clothingloyaltysetting",
            name="tier1_spend",
            field=models.DecimalField(
                decimal_places=2,
                default=5000,
                help_text="Total spend (Rs.) needed for tier-1 discount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="clothingloyaltysetting",
            name="tier2_spend",
            field=models.DecimalField(
                decimal_places=2,
                default=10000,
                help_text="Total spend (Rs.) needed for tier-2 discount (10%)",
                max_digits=10,
            ),
        ),
    ]
