# Generated by Django 5.2.11 on 2026-03-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_notification'),
        ('clothing', '0007_esewa_payment'),
    ]

    operations = [
    ]
