# Generated by Django 4.2.28 on 2026-03-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothing", "0008_merge_0005_notification_0007_esewa_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin (Owner/SuperAdmin)"),
                    ("CASHIER", "Cashier"),
                    ("ALL", "All Users"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("OFFER_CREATED", "Offer Created"),
                    ("OFFER_EXPIRING", "Offer Expiring Soon"),
                    ("OFFER_EXPIRED", "Offer Expired"),
                    ("LOW_STOCK", "Low Stock Alert"),
                    ("PURCHASE_RECEIVED", "Purchase Received"),
                    ("PAYMENT_COMPLETED", "Payment Completed"),
                    ("GENERAL", "General"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["business", "target_role", "is_read"],
                name="clothing_no_busines_b703e0_idx",
            ),
        ),
    ]
