# Generated by Django 4.2.28 on 2026-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothing", "0009_notification_target_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("OFFER_CREATED", "Offer Created"),
                    ("OFFER_EXPIRING", "Offer Expiring Soon"),
                    ("OFFER_EXPIRED", "Offer Expired"),
                    ("LOW_STOCK", "Low Stock Alert"),
                    ("PURCHASE_RECEIVED", "Purchase Received"),
                    ("PAYMENT_COMPLETED", "Payment Completed"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("GENERAL", "General"),
                ],
                max_length=30,
            ),
        ),
    ]
