# Generated by Django 5.2.11 on 2026-03-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_invoice_created_at_alter_order_created_at_and_more'),
        ('restaurant', '0003_receptioninvoice_receptionloyaltytransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptioninvoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_invoices', to='pos.order'),
        ),
    ]
