# Generated by Django 5.2.11 on 2026-03-30 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_business_citizenship_thumbnail_and_more'),
        ('restaurant', '0004_receptioninvoice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
