# Generated by Django 5.2.11 on 2026-03-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_business_citizenship_thumbnail_and_more'),
        ('restaurant', '0004_receptioninvoice_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diningtable',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tablecategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='tablecategory',
            unique_together={('business', 'code_prefix'), ('business', 'name')},
        ),
    ]
