# Generated by Django 5.2.11 on 2026-05-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_diningtable_options_and_more'),
        ('restaurant', '0005_restaurantnotification'),
    ]

    operations = [
    ]
