# Generated by Django 5.2.11 on 2026-03-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_merge_20260331_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantnotification',
            name='target_role',
            field=models.CharField(choices=[('ALL', 'All'), ('WAITER', 'Waiter'), ('KITCHEN', 'Kitchen'), ('CASHIER', 'Cashier')], default='ALL', max_length=20),
        ),
    ]
