# Generated by Django 5.2.11 on 2026-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('CASHIER', 'Cashier'), ('WAITER', 'Waiter'), ('KITCHEN', 'Kitchen')], max_length=30),
        ),
    ]
