# Generated by Django 5.2.11 on 2026-03-14 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=100)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY')], default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12 Hour'), ('24h', '24 Hour')], default='24h', max_length=10)),
                ('compact_mode', models.BooleanField(default=False)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('sound_notifications', models.BooleanField(default=True)),
                ('new_order_alert', models.BooleanField(default=True)),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('payment_alert', models.BooleanField(default=True)),
                ('rows_per_page', models.PositiveIntegerField(default=10)),
                ('auto_print_receipt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
