# Generated by Django 5.2.11 on 2026-03-15 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('english', 'English'), ('nepali', 'Nepali')], default='english', max_length=20)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=100)),
                ('rows_per_page', models.PositiveIntegerField(default=10)),
                ('email_notifications', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=False)),
                ('sound_alerts', models.BooleanField(default=False)),
                ('new_order_alert', models.BooleanField(default=False)),
                ('low_stock_alert', models.BooleanField(default=False)),
                ('auto_print_receipt', models.BooleanField(default=False)),
                ('compact_mode', models.BooleanField(default=False)),
                ('collapse_sidebar', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
