# Generated by Django 5.2.11 on 2026-03-28 14:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesstype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='citizenship_image',
            field=models.ImageField(upload_to=core.models.cloudinary_original_path),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='pan_image',
            field=models.ImageField(upload_to=core.models.cloudinary_original_path),
        ),
    ]
