# Generated by Django 5.2.11 on 2026-03-28 15:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_businessrequest_citizenship_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='citizenship_image',
            field=models.ImageField(max_length=512, upload_to=core.models.cloudinary_original_path),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='pan_image',
            field=models.ImageField(max_length=512, upload_to=core.models.cloudinary_original_path),
        ),
    ]
