# Generated by Django 5.2.11 on 2026-03-29 08:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_businessrequest_citizenship_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.cloudinary_original_path),
        ),
    ]
