# Generated by Django 5.2.11 on 2026-03-29 13:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
        migrations.AddField(
            model_name='business',
            name='citizenship_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.cloudinary_document_path),
        ),
        migrations.AddField(
            model_name='business',
            name='pan_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.cloudinary_document_path),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='citizenship_image',
            field=models.ImageField(max_length=512, upload_to=core.models.cloudinary_document_path),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='pan_image',
            field=models.ImageField(max_length=512, upload_to=core.models.cloudinary_document_path),
        ),
    ]
