# Generated by Django 5.2.11 on 2026-03-29 14:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_business_image_business_citizenship_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='citizenship_thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.cloudinary_document_thumbnail_path),
        ),
        migrations.AddField(
            model_name='business',
            name='pan_thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.cloudinary_document_thumbnail_path),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='citizenship_thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.cloudinary_document_thumbnail_path),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='pan_thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.cloudinary_document_thumbnail_path),
        ),
    ]
