# Generated by Django 5.2.11 on 2026-03-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_business_citizenship_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='citizenship_image',
        ),
        migrations.RemoveField(
            model_name='business',
            name='citizenship_thumbnail',
        ),
        migrations.RemoveField(
            model_name='business',
            name='pan_image',
        ),
        migrations.RemoveField(
            model_name='business',
            name='pan_thumbnail',
        ),
        migrations.RemoveField(
            model_name='businessrequest',
            name='citizenship_image',
        ),
        migrations.RemoveField(
            model_name='businessrequest',
            name='citizenship_thumbnail',
        ),
        migrations.RemoveField(
            model_name='businessrequest',
            name='pan_image',
        ),
        migrations.RemoveField(
            model_name='businessrequest',
            name='pan_thumbnail',
        ),
    ]
